### ISSUE TITLE
Missing files in riscv-tools

### ISSUE THREAD

**Issue by celuk** [CMU-SAFARI/PiDRAM#2]
There are missing files in [riscv-tools](https://github.com/CMU-SAFARI/PiDRAM/tree/master/fpga-zynq/rocket-chip/riscv-tools) and cause build errors. 

After copying these missing files, I am able to build [riscv-tools](https://github.com/CMU-SAFARI/PiDRAM/tree/master/fpga-zynq/rocket-chip/riscv-tools) successfully:

* I copied `target` folder from https://github.com/riscvarchive/riscv-binutils-gdb/tree/9b4d67248adb045caa8f166c59a0081867cc6cb2/gdb

```
riscv-tools/riscv-gnu-toolchain/riscv-binutils-gdb/gdb/target/target.h
riscv-tools/riscv-gnu-toolchain/riscv-binutils-gdb/gdb/target/resume.h
riscv-tools/riscv-gnu-toolchain/riscv-binutils-gdb/gdb/target/wait.h
riscv-tools/riscv-gnu-toolchain/riscv-binutils-gdb/gdb/target/waitstatus.h
riscv-tools/riscv-gnu-toolchain/riscv-binutils-gdb/gdb/target/waitstatus.c
```

* And, I copied `config.h` file from https://github.com/riscvarchive/riscv-newlib/tree/0bb64b9508bdbe3e2500a5f5efa5baec20838042/newlib/libc/include/sys

```
riscv-tools/riscv-newlib/newlib/libc/include/sys/config.h
```

Assuming the project based on latest commit of [ucb-bar fpga-zynq repository](https://github.com/ucb-bar/fpga-zynq) I copied the files from corresponding sub-repositories with corresponding commits.

**Comment by olgunataberk** [comment]
This looks like a good solution to a problem I unfortunately do not have the time to reproduce.

[9a48d2a](https://github.com/CMU-SAFARI/PiDRAM/commit/9a48d2a726ca6f25fbbff3bf2963f716c0de004f) now lists this problem under ``Known Issues'' and highlights your solution in the README.md.
